eureka:
  client:
    serviceUrl:
      defaultZone: http://202.115.161.211:17001/eureka/

server:
  port: 8763
  servlet:
    context-path: /usercenter



spring:
  application:
    name: service-usercenter
  # mysql 配置
  datasource:
    url: jdbc:mysql://202.115.161.211:13307/oj3?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: wzy
    password: wzy
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # redis 配置
  redis:
    host: 202.115.161.211
    port: 16379
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        max-wait: -1ms
        max-idle: 20
        min-idle: 2

# jwt 配置
jwt:
  secret_key: ok332shyuasdf
  # token 超时5分钟
  millisecond: 300000
  # 可刷新时间3天
  refresh_exp_millisecond: 259200000
  issuer: SwustOJ_JWT
  aud: swuster

# mail 配置
mail:
  smtp:
    host: mail.swust.edu.cn
  username: acm@swust.edu.cn
  password: csofswust
  sender: SWUST OJ 团队

# cache 配置
cache:
  millisecond: 7200000


# log 配置
logging:
  level:
    root: info
    com.kelab.usercenter.dal.dao: debug
  file: /usercerter.log

# mybatis 扫描路径
mybatis:
  mapper-locations: classpath:mapper/*.xml