spring:
  application:
    name: service-usercenter
  ## 选择运行环境
  profiles:
    active: dev
  # 文件上传
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

## 公共配置 ##
server:
  port: 8763
  servlet:
    context-path: /usercenter
# jwt 配置
jwt:
  secret_key: ok332shyuasdf
  # token 超时5分钟
  millisecond: 300000
  # 可刷新时间3天
  refresh_exp_millisecond: 259200000
  issuer: SwustOJ_JWT
  aud: swuster

## 文件后缀名
file-upload:
  access-file-extend: bmp,jpg,jpeg,png,gif,pdf

# mail 配置
mail:
  smtp:
    host: mail.swust.edu.cn
  username: acm@swust.edu.cn
  password: csofswust
  sender: SWUST OJ 团队

# cache 配置
cache:
  millisecond: 7200000

# log 配置
logging:
  level:
    root: info
    com.kelab.usercenter.dal.dao: debug
  file: ./logs/usercenter.log

# mybatis 扫描路径
mybatis:
  mapper-locations: classpath:mapper/*.xml