eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.115:7002/eureka/

spring:
  # mysql 配置
  datasource:
    url: jdbc:mysql://192.168.0.116:3306/oj4?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: kelab
    password: Swust.kelab123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # redis 配置
  redis:
    host: 192.168.0.115
    port: 6379
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2

fdfs:
  so-timeout: 1501
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
    - 192.168.0.97:22122