eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.115:7002/eureka/

spring:
  # mysql 配置
  datasource:
    url: jdbc:mysql://192.168.0.115:3306/oj3?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: wzy
    password: wzy
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # redis 配置
  redis:
    host: 192.168.0.115
    port: 6379
    database: 0
    timeout: 5000
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2