eureka:
    client:
        serviceUrl:
            defaultZone: http://202.115.161.211:17001/eureka/

server:
    port: 8763
    servlet:
        context-path: /usercenter



spring:
    application:
        name: service-usercenter
    # 数据库连接
    datasource:
        url: jdbc:mysql://202.115.161.211:13307/oj3?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: wzy
        password: wzy
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
jwt:
    secret_key: ok332shyuasdf
    millisecond: 1800000
    jwt_issuer: SwustOJ_JWT
    jwt_aud: swuster
# mybatis 扫描路径
mybatis:
    mapper-locations: classpath:mapper/*.xml